apiVersion: v1
kind: Pod
metadata:
  name: productsapi
  labels:
    name: productsapi
spec:
  containers:
  - name: productsapi
    image: acrmbi.azurecr.io/productsapi:latest
    imagePullPolicy: Always
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  imagePullSecrets:
    - name:  regcred