// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductsAPI.Repositories;

namespace ProductsAPI.Migrations
{
    [DbContext(typeof(ProductsDbContext))]
    [Migration("20200925185229_AddProducts")]
    partial class AddProducts
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductsAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Tennis racket",
                            Price = 75.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hockey stick",
                            Price = 34.060000000000002
                        },
                        new
                        {
                            Id = 3,
                            Name = "Basketball",
                            Price = 24.989999999999998
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ice skates",
                            Price = 199.99000000000001
                        },
                        new
                        {
                            Id = 5,
                            Name = "Baseball glove",
                            Price = 29.370000000000001
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
