apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: productsapi
  labels:
    name: productsapi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: productsapi
  template:
    metadata:
      labels:
        app: productsapi
    spec:
      containers:
      - name: productsapi
        image: acrmbi.azurecr.io/productsapi:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name:  regcred

---

  apiVersion: v1
  kind: Service
  metadata:
    name: productsapi-nodeport
  spec:
    type: NodePort
    selector:
      app: productsapi
    ports:
      - protocol: TCP
        port: 80
        targetPort: 80